cors:
  originPatterns: http://localhost:8080,https://erudio.com.br,http://localhost:3000
security:
  jwt:
    token:
      secret-key: 53cr37 #//-> nossa secret
      expire-length: 3600000 #// -> quanto tempo esse token irá durar? tem que ser em millisegundos
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
    username: root
    password: 99620530
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    open-in-view: false

spring-doc:
  athsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true
